{"error":{},"level":"error","message":"uncaughtException: Something failed during startup. \nError: Something failed during startup. \n    at Object.<anonymous> (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js:41:7)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","stack":"Error: Something failed during startup. \n    at Object.<anonymous> (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js:41:7)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","exception":true,"date":"Mon Aug 05 2019 11:34:14 GMT-0500 (Central Daylight Time)","process":{"pid":22560,"uid":null,"gid":null,"cwd":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.16.0","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js"],"memoryUsage":{"rss":61870080,"heapTotal":59547648,"heapUsed":28038024,"external":18668958}},"os":{"loadavg":[0,0,0],"uptime":349349},"trace":[{"column":7,"file":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js","function":null,"line":41,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":776,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":787,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":653,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":593,"method":null,"native":false},{"column":3,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":585,"method":"_load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"Module.runMain","line":829,"method":"runMain","native":false},{"column":19,"file":"internal/bootstrap/node.js","function":"startup","line":283,"method":null,"native":false},{"column":3,"file":"internal/bootstrap/node.js","function":"bootstrapNodeJSCore","line":622,"method":null,"native":false}]}
{"error":{},"level":"error","message":"uncaughtException: Something failed during startup. \nError: Something failed during startup. \n    at Object.<anonymous> (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js:41:7)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","stack":"Error: Something failed during startup. \n    at Object.<anonymous> (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js:41:7)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","exception":true,"date":"Mon Aug 05 2019 11:34:41 GMT-0500 (Central Daylight Time)","process":{"pid":26880,"uid":null,"gid":null,"cwd":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.16.0","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js"],"memoryUsage":{"rss":61751296,"heapTotal":59547648,"heapUsed":28830464,"external":18738469}},"os":{"loadavg":[0,0,0],"uptime":349375},"trace":[{"column":7,"file":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js","function":null,"line":41,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":776,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":787,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":653,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":593,"method":null,"native":false},{"column":3,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":585,"method":"_load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"Module.runMain","line":829,"method":"runMain","native":false},{"column":19,"file":"internal/bootstrap/node.js","function":"startup","line":283,"method":null,"native":false},{"column":3,"file":"internal/bootstrap/node.js","function":"bootstrapNodeJSCore","line":622,"method":null,"native":false}]}
{"error":{},"level":"error","message":"uncaughtException: Cannot read property 'exit' of undefined\nTypeError: Cannot read property 'exit' of undefined\n    at Object.<anonymous> (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js:22:95)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","stack":"TypeError: Cannot read property 'exit' of undefined\n    at Object.<anonymous> (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js:22:95)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","exception":true,"date":"Mon Aug 05 2019 11:35:46 GMT-0500 (Central Daylight Time)","process":{"pid":23372,"uid":null,"gid":null,"cwd":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.16.0","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js"],"memoryUsage":{"rss":61222912,"heapTotal":59023360,"heapUsed":28477832,"external":18738469}},"os":{"loadavg":[0,0,0],"uptime":349441},"trace":[{"column":95,"file":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js","function":null,"line":22,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":776,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":787,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":653,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":593,"method":null,"native":false},{"column":3,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":585,"method":"_load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"Module.runMain","line":829,"method":"runMain","native":false},{"column":19,"file":"internal/bootstrap/node.js","function":"startup","line":283,"method":null,"native":false},{"column":3,"file":"internal/bootstrap/node.js","function":"bootstrapNodeJSCore","line":622,"method":null,"native":false}]}
{"error":{},"level":"error","message":"uncaughtException: Something failed during startup. \nError: Something failed during startup. \n    at Object.<anonymous> (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js:41:7)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","stack":"Error: Something failed during startup. \n    at Object.<anonymous> (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js:41:7)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","exception":true,"date":"Mon Aug 05 2019 11:36:11 GMT-0500 (Central Daylight Time)","process":{"pid":26656,"uid":null,"gid":null,"cwd":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.16.0","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js"],"memoryUsage":{"rss":61808640,"heapTotal":59023360,"heapUsed":28845400,"external":18738469}},"os":{"loadavg":[0,0,0],"uptime":349466},"trace":[{"column":7,"file":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js","function":null,"line":41,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":776,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":787,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":653,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":593,"method":null,"native":false},{"column":3,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":585,"method":"_load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"Module.runMain","line":829,"method":"runMain","native":false},{"column":19,"file":"internal/bootstrap/node.js","function":"startup","line":283,"method":null,"native":false},{"column":3,"file":"internal/bootstrap/node.js","function":"bootstrapNodeJSCore","line":622,"method":null,"native":false}]}
{"error":{},"level":"error","message":"uncaughtException: Something failed during startup. \nError: Something failed during startup. \n    at Object.<anonymous> (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js:41:7)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","stack":"Error: Something failed during startup. \n    at Object.<anonymous> (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js:41:7)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","exception":true,"date":"Mon Aug 05 2019 11:48:03 GMT-0500 (Central Daylight Time)","process":{"pid":16604,"uid":null,"gid":null,"cwd":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.16.0","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js"],"memoryUsage":{"rss":61722624,"heapTotal":59547648,"heapUsed":28705128,"external":18723024}},"os":{"loadavg":[0,0,0],"uptime":350178},"trace":[{"column":7,"file":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js","function":null,"line":41,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":776,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":787,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":653,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":593,"method":null,"native":false},{"column":3,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":585,"method":"_load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"Module.runMain","line":829,"method":"runMain","native":false},{"column":19,"file":"internal/bootstrap/node.js","function":"startup","line":283,"method":null,"native":false},{"column":3,"file":"internal/bootstrap/node.js","function":"bootstrapNodeJSCore","line":622,"method":null,"native":false}]}
{"error":{"name":"MongoNetworkError","errorLabels":["TransientTransactionError"]},"level":"error","message":"uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\nMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\topologies\\server.js:431:11)\n    at Pool.emit (events.js:198:13)\n    at connect (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\connection\\pool.js:557:14)\n    at makeConnection (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\connection\\connect.js:39:11)\n    at callback (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\connection\\connect.js:261:5)\n    at Socket.err (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\connection\\connect.js:286:7)\n    at Object.onceWrapper (events.js:286:20)\n    at Socket.emit (events.js:198:13)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\topologies\\server.js:431:11)\n    at Pool.emit (events.js:198:13)\n    at connect (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\connection\\pool.js:557:14)\n    at makeConnection (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\connection\\connect.js:39:11)\n    at callback (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\connection\\connect.js:261:5)\n    at Socket.err (C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\connection\\connect.js:286:7)\n    at Object.onceWrapper (events.js:286:20)\n    at Socket.emit (events.js:198:13)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","exception":true,"date":"Fri Aug 09 2019 07:41:37 GMT-0500 (Central Daylight Time)","process":{"pid":26172,"uid":null,"gid":null,"cwd":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.16.0","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\index.js"],"memoryUsage":{"rss":61648896,"heapTotal":59547648,"heapUsed":21946304,"external":18278996}},"os":{"loadavg":[0,0,0],"uptime":680992},"trace":[{"column":11,"file":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\topologies\\server.js","function":null,"line":431,"method":null,"native":false},{"column":13,"file":"events.js","function":"Pool.emit","line":198,"method":"emit","native":false},{"column":14,"file":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\connection\\pool.js","function":"connect","line":557,"method":null,"native":false},{"column":11,"file":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\connection\\connect.js","function":"makeConnection","line":39,"method":null,"native":false},{"column":5,"file":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\connection\\connect.js","function":"callback","line":261,"method":null,"native":false},{"column":7,"file":"C:\\Users\\mattp\\Documents\\Dev\\Vidly_Node.js\\node_modules\\mongodb-core\\lib\\connection\\connect.js","function":"Socket.err","line":286,"method":"err","native":false},{"column":20,"file":"events.js","function":"Object.onceWrapper","line":286,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"Socket.emit","line":198,"method":"emit","native":false},{"column":8,"file":"internal/streams/destroy.js","function":"emitErrorNT","line":91,"method":null,"native":false},{"column":3,"file":"internal/streams/destroy.js","function":"emitErrorAndCloseNT","line":59,"method":null,"native":false},{"column":19,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":63,"method":"_tickCallback","native":false}]}
